//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class HumanPickUpAmmo : ReactiveBehaviour
{
	
	HumanState humanState;
	HumanShooting playerShooting;
	
	void Awake(){
		playerShooting = transform.root.GetComponent<HumanShooting> ();
		humanState = transform.root.GetComponent <HumanState> ();
	}
	
	protected override bool IsInSituation ()
	{
		return humanState.IsOnAmmo ();
	}
	
	protected override void Execute ()
	{
		
		GameObject ammoObject = humanState.ammoSeen;
		Debug.Log ("On Ammo!");
		//Due to non-deterministic environment
		if (ammoObject == null) {
			humanState.onAmmo = false;
			humanState.sawAmmo = false;
			return;
		}
		
		Ammo ammo = ammoObject.GetComponent<Ammo> ();

		playerShooting.GrabAmmo(ammo.GrabAmmo ());
		
		humanState.onAmmo = false;
		humanState.sawAmmo = false;
		
	}
}


